from pathlib import Path
import sys
from typing import Literal
from cyclopts import App
import tomli

from .assignment import Assignment, AssignmentConfig, AssignmentMetadata
from .grades import AssignmentGrade
from .gradescope_model import GradescopeMetadata
from .gradescope_output_model import GradescopeOutput

from .local_grading import LocalAutograderOutput
from .submission import Submission

app = App(
    help="A fun autograder management system for the whole family.",
    help_format="md",
    help_formatter="plain",
    help_on_error=True,
)

ASSIGNMENT_DIR = Path(".")
ASSIGNMENT_FILES_DIR = "grading-files"
ASSIGNMENT_CONFIG_TOML = "zucchini.toml"
ASSIGNMENT_CONFIG_JSON = "zucchini.json"

def _get_assignment_cfg(grading_dir: Path) -> AssignmentConfig:
    # Try reading from TOML
    try:
        with open(grading_dir / ASSIGNMENT_CONFIG_TOML, "rb") as f:
            data = tomli.load(f) 
            return AssignmentConfig.model_validate(data)
    except FileNotFoundError:
        pass

    # Try reading from JSON
    try:
        with open(grading_dir / ASSIGNMENT_CONFIG_JSON, "rb") as f:
            return AssignmentConfig.model_validate_json(f.read())
    except FileNotFoundError:
        pass

    raise FileNotFoundError(f"Missing configuration file {ASSIGNMENT_CONFIG_TOML} in {grading_dir}")
def _get_assignment(submission_dir: Path, grading_dir: Path, gs_metadata_fp: Path) -> tuple[Assignment, Submission]:
    # Get metadata:
    submission_created_at = None
    metadata = AssignmentMetadata()

    # Load metadata from Gradescope submission_metadata.json file:
    try:
        with open(gs_metadata_fp, "rb") as f:
            gs_metadata = GradescopeMetadata.model_validate_json(f.read())
            
            metadata = gs_metadata.as_metadata()
            submission_created_at = gs_metadata.created_at
    except FileNotFoundError:
        pass

    # Get config:
    config = _get_assignment_cfg(grading_dir)
    return (
        Assignment(config, grading_dir / ASSIGNMENT_FILES_DIR, metadata),
        Submission(submission_dir, submission_created_at)
    )

@app.command
def grade(
    submission_path: Path = Path("/autograder/submission"),
    metadata_path: Path = Path("/autograder/metadata")
):
    """
    Grades a submission, located at the specified submission path.

    Parameters
    ----------
    submission_path : Path, optional
        The path of the submission as generated by Gradescope.
    metadata_path : Path, optional
        The path of the submission metadata.
        This is the submission_metadata.json format that Gradescope uses.
    """
    assignment, submission = _get_assignment(submission_path, ASSIGNMENT_DIR, metadata_path)
    grade = assignment.grade(submission)
    print(grade.model_dump_json())

@app.command()
def export(
    format_: Literal["text", "gradescope"]
):
    """
    Convert component grades to some format JSON.

    Bridge the gap between component results provided obtained with
    `zucc grade-submission' (plus Gradescope submission metadata) and a
    Gradescope JSON result. Will read component grades JSON from stdin
    and spit out Gradescope JSON on stdout.

    FIXME: old format
    Usual usage:
    zucc grade-submission /autograder/submission \\
        | zucc gradescope bridge /autograder/submission_metadata.json \\
        >/autograder/results/results.json
    """
    grade = AssignmentGrade.model_validate_json(sys.stdin.read())

    if format_ == "text":
        output = LocalAutograderOutput.from_grade(grade)
        print(output)
    elif format_ == "gradescope":
        output = GradescopeOutput.from_grade(grade)
        print(output.model_dump_json())
    else:
        raise ValueError(f"Invalid format {format_!r}")

# @app.command()
# def generate(
#     format_: Literal["gradescope_zip", "gradescope_docker"],
#     out_path: Path,
#     wheel_path: Path,
# ):
#     if format_ == "gradescope_zip":
#         assignment = state.get_assignment()
#         autograder_zip = GradescopeAutograderZip(
#             path=state.assignment_directory,
#             prerequisites=assignment.list_prerequisites(),
#             extra_setup_commands=assignment
#                                     .list_extra_setup_commands(),
#             needs_display=assignment.needs_display(),
#             wheel_path=wheel_path)
#         autograder_zip.write_zip(out_path)
#     elif format_ == "gradescope_docker":
#         raise NotImplementedError()
#     else:
#         raise ValueError(f"Invalid template format {format_!r}")
#     pass

if __name__ == "__main__":
    app()